remove_default_trades: true

maximum_unique_trade_offers:
  player_heads: 3
  items: 2
  decoration_heads: 20

whitelist:
  enable_synchronization: true
  number_of_player_head_offers: 3
  heads_rewarded_per_trade: 1
  maximum_number_of_trades: 64
  experience_rewarded_for_each_trade: 0
  trade_price_multiplier: 0

  price:
    item1:
      minecraft_id: "diamond"
      quantity: 1